"""Loads the 3 production artifacts and exposes plain-Python predict methods
for the Olist customer intelligence web app.

Model/metadata files must sit alongside this module in the same folder:
    kmeans_segmentation.joblib, kmeans_scaler.joblib, segment_names.json,
    churn_gb_tuned.joblib, churn_feature_cols.json,
    repeat_purchase_svm.joblib, manifest.json

These are generated by running Team3_Deployment_NextSteps.ipynb (Section 2)
against the team's real Drive data and copying the deployment_models/ folder
it produces into this repo.
"""
import json
import os

import numpy as np
import pandas as pd
import joblib

_HERE = os.path.dirname(os.path.abspath(__file__))


def _load(name):
    return joblib.load(os.path.join(_HERE, name))


def _load_json(name):
    with open(os.path.join(_HERE, name)) as f:
        return json.load(f)


class OlistCustomerIntelligence:
    """Single entry point the web app (or any future backend) talks to."""

    def __init__(self):
        self.manifest = _load_json('manifest.json')

        self.seg_model = _load('kmeans_segmentation.joblib')
        self.seg_scaler = _load('kmeans_scaler.joblib')
        self.segment_names = _load_json('segment_names.json')

        self.churn_model = _load('churn_gb_tuned.joblib')
        self.churn_feature_cols = _load_json('churn_feature_cols.json')

        self.repeat_model = _load('repeat_purchase_svm.joblib')

    def predict_segment(self, recency, frequency, monetary):
        """Which customer segment does this recency/frequency/monetary profile fall into?"""
        monetary_log = np.log1p(monetary)
        X = pd.DataFrame([{
            'recency': recency,
            'frequency': frequency,
            'monetary_log': monetary_log,
        }])
        X_scaled = self.seg_scaler.transform(X)
        cluster_id = int(self.seg_model.predict(X_scaled)[0])
        return {
            'cluster_id': cluster_id,
            'segment_name': self.segment_names.get(str(cluster_id), 'Unknown'),
        }

    def predict_churn_risk(self, frequency, monetary, avg_review_score,
                            avg_delivery_days, on_time_rate, avg_payment_installments):
        """Probability this customer goes 180+ days without another purchase.
        recency is intentionally NOT an input - it defines the label, so
        including it would leak the answer into the model."""
        monetary_log = np.log1p(monetary)
        row = {
            'frequency': frequency,
            'monetary_log': monetary_log,
            'avg_review_score': avg_review_score,
            'avg_delivery_days': avg_delivery_days,
            'on_time_rate': on_time_rate,
            'avg_payment_installments': avg_payment_installments,
        }
        X = pd.DataFrame([row])[self.churn_feature_cols]
        proba = float(self.churn_model.predict_proba(X)[0, 1])
        return {
            'churn_probability': round(proba, 4),
            'risk_label': 'High' if proba >= 0.6 else 'Medium' if proba >= 0.3 else 'Low',
        }

    def predict_repeat_purchase(self, price, freight_value, payment_installments,
                                 payment_type, product_category_name, customer_state, on_time):
        """Probability a first-time buyer places a second order.
        Only uses what's known right after checkout - no purchase history required."""
        X = pd.DataFrame([{
            'price_capped': price,
            'freight_value': freight_value,
            'payment_installments': payment_installments,
            'payment_type': payment_type,
            'product_category_name': product_category_name,
            'customer_state': customer_state,
            'on_time': on_time,
        }])
        proba = float(self.repeat_model.predict_proba(X)[0, 1])
        return {
            'repeat_purchase_probability': round(proba, 4),
            'label': 'Likely to return' if proba >= 0.5 else 'Unlikely to return',
        }

    def get_segment_profile(self, cluster_id):
        """Average recency/frequency/monetary for a given segment, recovered from
        the fitted KMeans centroid - no extra artifact file needed, since the
        centroid and the scaler used to fit it are both already loaded."""
        center_scaled = self.seg_model.cluster_centers_[cluster_id].reshape(1, -1)
        recency, frequency, monetary_log = self.seg_scaler.inverse_transform(center_scaled)[0]
        return {
            'recency': float(recency),
            'frequency': float(frequency),
            'monetary': float(np.expm1(monetary_log)),
        }

    def get_all_segment_profiles(self):
        """Segment profile for every cluster, keyed by segment name."""
        n_clusters = len(self.seg_model.cluster_centers_)
        return {
            self.segment_names.get(str(cid), f'Cluster {cid}'): self.get_segment_profile(cid)
            for cid in range(n_clusters)
        }

    def get_churn_feature_importance(self):
        """(feature_name, importance) pairs from the fitted model, high to low.
        Read directly off the model object - nothing extra to save or load."""
        importances = self.churn_model.feature_importances_
        pairs = list(zip(self.churn_feature_cols, [float(i) for i in importances]))
        pairs.sort(key=lambda x: x[1], reverse=True)
        return pairs
